import type { components } from './vtexCatalogTypes';

/**
 * Named shapes from VTEX's own Catalog API schema, generated by `pnpm types:vtex`. Reach for these
 * rather than describing a response by hand: a field VTEX adds or renames then shows up as a type
 * error instead of as data quietly going missing.
 *
 * The schema is not a perfect record of the API, so a shape is corrected below where the live
 * account disagrees with it. Correct in the open, with the reason — never by widening to `any`.
 */
export type VtexCatalogCategoryTree = components['schemas']['GetCategoryTree'];
export type VtexCatalogCategory = components['schemas']['Category'];
export type VtexCatalogSkuSpecification = components['schemas']['SkuSpecification'];
export type VtexCatalogProductSpecification = components['schemas']['ProductSpecification'];
export type VtexCatalogSkuContext = components['schemas']['GetSKUandContext'];
